version: "3"

services:
  web:
    image: janajankovic/iis-flask:latest
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      MLFLOW_TRACKING_PASSWORD: ${MLFLOW_TRACKING_PASSWORD}
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      MLFLOW_TRACKING_USERNAME: ${MLFLOW_TRACKING_USERNAME}
      MONGO_URI: ${MONGO_URI}
    ports:
      - "5000:5000"
    restart: always
  frontend:
    image: janajankovic/iis-ng:latest
    ports:
      - "4200:4200"
    restart: always
