version: "3"

services:
  web:
    image: janajankovic/iis-flask:latest
    ports:
      - "5000:5000"
    restart: always
  frontend:
    image: janajankovic/iis-ng:latest
    ports:
      - "4200:4200"
    restart: always
