name: my-app
services:
  web:
    build: .
    image: janajankovic/iis-flask:latest
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
    volumes:
      - .:/app
  frontend:
    build: .
    image: janajankovic/iis-ng:latest
    ports:
      - "4200:4200"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
