name: Data Workflow

on:
  push:
    branches:
      - main

  schedule:
    - cron: "* 1 * * *"

jobs:
  fetch_air_data:
    runs-on: ubuntu-latest
    outputs:
      sha_new: ${{steps.sha_new.outputs.SHA_NEW}}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.5"
          token: ${{ secrets.TKN }}

      - uses: iterative/setup-dvc@v1

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --no-root

      - name: Setup Dagshub
        run: |
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user ${{ secrets.DAGSHUB_USERNAME }}
          dvc remote modify origin --local password ${{ secrets.DAGSHUB_TOKEN }}

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "janajankovic@users.noreply.github.com"

      - name: Pull changes
        run: |
          git pull
          dvc pull

      - name: Run tests
        run: poetry run pytest test/test_air_data.py

      - name: Fetch data
        run: poetry run fetch_air_data

      - name: Commit changes
        run: |
          dvc add data
          git add .
          git commit -m 'Github Actions Bot Commit data'
          git push
          dvc push -r origin

