name: Workflow

on:
  push:
    branches:
      - main

  schedule:
    - cron: "59 * * * *"

jobs:
  hourly-job:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.1"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch data
        run: python ./src/data/fetch_data.py

      - name: Train model
        run: python ./src/models/predict_model.py

  push-job:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.1"
          token: ${{ secrets.TKN }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch data
        run: python ./src/data/fetch_data.py

      - name: Train model
        run: python ./src/models/predict_model.py

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "janajankovic@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add .
          git commit -m "GitHub Actions Bot Commit Changes"
          git push origin main

      - name: Run tests
        run: pytest
