name: Workflow

on:
  push:
    branches:
      - main

  schedule:
    - cron: "* 1 * * *"

jobs:
  hourly-data-update-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.1"
          token: ${{ secrets.TKN }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch data
        run: python ./src/data/fetch_data.py

      - name: Train model
        run: python ./src/models/predict_model.py

  push-job:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.1"
          token: ${{ secrets.TKN }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
